package fingerprint

// builtinRule is one substring match against the lowercased name haystack (see buildNameHaystack).
type builtinRule struct {
	pattern    string
	kind       string
	confidence string
	text       string
	ruleID     string
}

// builtinNameRules is a large curated list of vendor / product / mDNS tokens.
// Prefer distinctive substrings; avoid very generic words (false positives).
// Order does not affect matching (all matches apply); dedupe removes identical rows.
var builtinNameRules = []builtinRule{
	// Google / Nest / Cast / Android TV
	{"chromecast", "family", "medium", "Likely Google Cast / Chromecast or Google TV stack (from name token).", "cast_chromecast"},
	{"googlecast", "family", "medium", "Likely Google Cast device (mDNS service token).", "cast_googlecast"},
	{"_googlecast._tcp", "family", "medium", "Likely Google Cast (mDNS service type).", "cast_srv_googlecast"},
	{"google-home", "family", "medium", "Likely Google Home / Nest Audio–class speaker (from name token).", "nest_google_home"},
	{"googlehome", "family", "medium", "Likely Google Home–class device (from name token).", "nest_googlehome"},
	{"nest-mini", "family", "medium", "Likely Google Nest Mini (from name token).", "nest_mini"},
	{"nest-audio", "family", "medium", "Likely Google Nest Audio (from name token).", "nest_audio"},
	{"nest-hub", "family", "medium", "Likely Google Nest Hub display (from name token).", "nest_hub"},
	{"nest-doorbell", "family", "medium", "Likely Google Nest doorbell (from name token).", "nest_doorbell"},
	{"nest-cam", "family", "medium", "Likely Google Nest camera (from name token).", "nest_cam"},
	{"nestwifi", "family", "medium", "Likely Google Nest Wi-Fi (from name token).", "net_nestwifi"},
	{"nest wifi", "family", "medium", "Likely Google Nest Wi-Fi (from name token).", "net_nestwifi_space"},
	{"androidtv", "family", "medium", "Likely Android TV or Google TV device (from name token).", "cast_androidtv"},
	{"android-tv", "family", "medium", "Likely Android TV device (from name token).", "cast_android_tv"},
	{"atv", "family", "low", "Possibly Android TV or Apple TV abbreviation in hostname (ambiguous).", "tv_atv_ambiguous"},
	{"shield", "family", "low", "Possibly NVIDIA Shield TV (from name token).", "nvidia_shield"},
	{"nvidia", "family", "low", "Possibly NVIDIA Shield or Jetson (from name token).", "nvidia_generic"},

	// Amazon
	{"echo-dot", "family", "medium", "Likely Amazon Echo Dot (from name token).", "amz_echo_dot"},
	{"echo-show", "family", "medium", "Likely Amazon Echo Show (from name token).", "amz_echo_show"},
	{"echo-", "family", "low", "Possibly Amazon Echo-family speaker (from name token).", "amz_echo"},
	{"amazon-", "family", "low", "Possibly Amazon Echo / Fire / Ring–class device (hostname prefix).", "amz_prefix"},
	{"firetv", "family", "medium", "Likely Amazon Fire TV (from name token).", "amz_firetv"},
	{"fire-tv", "family", "medium", "Likely Amazon Fire TV (from name token).", "amz_fire_tv"},
	{"firestick", "family", "medium", "Likely Amazon Fire TV Stick (from name token).", "amz_firestick"},
	{"afts", "family", "low", "Possibly Amazon Fire TV internal hostname token (AFT*).", "amz_afts"},
	{"aftb", "family", "low", "Possibly Amazon Fire TV internal hostname token.", "amz_aftb"},
	{"aftm", "family", "low", "Possibly Amazon Fire TV Stick internal hostname token.", "amz_aftm"},
	{"kindle", "family", "medium", "Likely Amazon Kindle (from name token).", "amz_kindle"},
	{"_amzn-alexa._tcp", "family", "medium", "Likely Amazon Alexa-capable device (mDNS service type).", "amz_mdns_alexa"},
	{"_amzn-wss._tcp", "family", "medium", "Likely Amazon device (mDNS WSS service).", "amz_mdns_wss"},

	// Apple
	{"homepod", "family", "high", "Likely Apple HomePod (from name token).", "apple_homepod"},
	{"appletv", "family", "high", "Likely Apple TV (from name token).", "apple_tv"},
	{"apple-tv", "family", "high", "Likely Apple TV (from name token).", "apple_tv_dash"},
	{"ipad", "family", "low", "Possibly Apple iPad (from hostname; many networks).", "apple_ipad"},
	{"iphone", "family", "low", "Possibly Apple iPhone (from hostname).", "apple_iphone"},
	{"macbook", "family", "low", "Possibly Apple MacBook (from hostname).", "apple_macbook"},
	{"imac", "family", "low", "Possibly Apple iMac (from hostname).", "apple_imac"},
	{"_airplay._tcp", "family", "medium", "Likely AirPlay receiver (mDNS service type).", "apple_mdns_airplay"},
	{"_raop._tcp", "family", "medium", "Likely AirTunes / AirPlay audio (mDNS RAOP).", "apple_mdns_raop"},
	{"_companion-link._tcp", "family", "medium", "Likely Apple HomeKit companion (mDNS).", "apple_mdns_companion"},
	{"_sleep-proxy._udp", "family", "low", "Possibly Apple Bonjour sleep proxy (mDNS).", "apple_mdns_sleep"},

	// Streaming / gaming
	{"roku", "family", "medium", "Likely Roku or Roku-based TV/streaming (from name token).", "stream_roku"},
	{"tivo", "family", "medium", "Likely TiVo DVR (from name token).", "stream_tivo"},
	{"xbox", "family", "medium", "Likely Microsoft Xbox console (from name token).", "game_xbox"},
	{"xboxone", "family", "medium", "Likely Xbox One family (from name token).", "game_xboxone"},
	{"playstation", "family", "medium", "Likely Sony PlayStation (from name token).", "game_ps"},
	{"ps5", "family", "medium", "Likely Sony PS5 (from name token).", "game_ps5"},
	{"ps4", "family", "medium", "Likely Sony PS4 (from name token).", "game_ps4"},
	{"nintendo", "family", "medium", "Likely Nintendo console (from name token).", "game_nintendo"},
	{"switch", "family", "low", "Possibly Nintendo Switch (ambiguous with many “switch” products).", "game_switch_ambiguous"},
	{"steamdeck", "family", "medium", "Likely Steam Deck (from name token).", "game_steamdeck"},
	{"steamlink", "family", "medium", "Likely Steam Link (from name token).", "game_steamlink"},

	// Mesh / routers / APs (consumer)
	{"eero", "family", "high", "Likely eero mesh Wi-Fi (from name token).", "net_eero"},
	{"orbi", "family", "medium", "Likely NETGEAR Orbi mesh (from name token).", "net_orbi"},
	{"nighthawk", "family", "medium", "Likely NETGEAR Nighthawk router (from name token).", "net_nighthawk"},
	{"netgear", "family", "medium", "Likely NETGEAR router or extender (from name token).", "net_netgear"},
	{"tplink", "family", "medium", "Likely TP-Link router or IoT (from name token).", "net_tplink"},
	{"tp-link", "family", "medium", "Likely TP-Link device (from name token).", "net_tplink_dash"},
	{"archer", "family", "low", "Possibly TP-Link Archer router (common hostname).", "net_archer"},
	{"deco", "family", "medium", "Likely TP-Link Deco mesh (from name token).", "net_deco"},
	{"asus", "family", "medium", "Likely ASUS router or mesh node (from name token).", "net_asus"},
	{"rt-ax", "family", "low", "Possibly ASUS Wi-Fi 6 router model in hostname.", "net_asus_ax"},
	{"linksys", "family", "medium", "Likely Linksys router or Velop node (from name token).", "net_linksys"},
	{"velop", "family", "medium", "Likely Linksys Velop mesh (from name token).", "net_velop"},
	{"fritz", "family", "medium", "Likely AVM FRITZ!Box router (from name token).", "net_fritz"},
	{"fritz.box", "family", "medium", "Likely AVM FRITZ!Box (from hostname).", "net_fritzbox"},
	{"vodafone", "family", "low", "Possibly ISP CPE (Vodafone-branded) from hostname.", "net_vodafone"},
	{"arris", "family", "medium", "Likely Arris cable modem / gateway (from name token).", "net_arris"},
	{"hitron", "family", "medium", "Likely Hitron cable modem / gateway (from name token).", "net_hitron"},
	{"technicolor", "family", "medium", "Likely Technicolor / ISP gateway (from name token).", "net_technicolor"},
	{"sagemcom", "family", "medium", "Likely Sagemcom ISP gateway (from name token).", "net_sagemcom"},
	{"zyxel", "family", "medium", "Likely Zyxel router or NAS (from name token).", "net_zyxel"},
	{"mikrotik", "family", "high", "Likely MikroTik RouterOS device (from name token).", "net_mikrotik"},
	{"routeros", "family", "high", "Likely MikroTik RouterOS (from name token).", "net_routeros"},
	{"unifi", "family", "medium", "Likely Ubiquiti UniFi gear (from name token).", "net_unifi"},
	{"ubnt", "family", "medium", "Likely Ubiquiti device (from name token).", "net_ubnt"},
	{"amplifi", "family", "medium", "Likely Ubiquiti AmpliFi mesh (from name token).", "net_amplifi"},
	{"edgeos", "family", "medium", "Likely Ubiquiti EdgeRouter / EdgeOS (from name token).", "net_edgeos"},
	{"edgerouter", "family", "medium", "Likely Ubiquiti EdgeRouter (from name token).", "net_edgerouter"},
	{"dream machine", "family", "medium", "Likely Ubiquiti Dream Machine (from name token).", "net_udm_space"},
	{"udm-", "family", "low", "Possibly Ubiquiti Dream Machine (hostname prefix).", "net_udm"},
	{"u6-", "family", "low", "Possibly Ubiquiti UniFi Wi-Fi 6 AP model token.", "net_u6"},
	{"openwrt", "family", "high", "Likely OpenWrt router (from name token).", "net_openwrt"},
	{"lede", "family", "medium", "Likely LEDE/OpenWrt fork (from name token).", "net_lede"},
	{"dd-wrt", "family", "medium", "Likely DD-WRT router (from name token).", "net_ddwrt"},
	{"glinet", "family", "medium", "Likely GL.iNet travel router (from name token).", "net_glinet"},
	{"gl-mt", "family", "low", "Possibly GL.iNet router model in hostname.", "net_gl_mt"},
	{"peplink", "family", "medium", "Likely Peplink / Pepwave router (from name token).", "net_peplink"},
	{"fortigate", "family", "medium", "Likely Fortinet FortiGate (from name token).", "net_fortigate"},
	{"pfsense", "family", "high", "Likely pfSense firewall/router (from name token).", "net_pfsense"},
	{"opnsense", "family", "high", "Likely OPNsense firewall/router (from name token).", "net_opnsense"},
	{"omada", "family", "medium", "Likely TP-Link Omada controller or AP (from name token).", "net_omada"},

	// NAS / storage
	{"synology", "family", "high", "Likely Synology NAS or router (from name token).", "nas_synology"},
	{"diskstation", "family", "high", "Likely Synology DiskStation (from name token).", "nas_diskstation"},
	{"qnap", "family", "high", "Likely QNAP NAS (from name token).", "nas_qnap"},
	{"turbo-", "family", "low", "Possibly QNAP Turbo NAS model prefix in hostname.", "nas_qnap_turbo"},
	{"truenas", "family", "high", "Likely TrueNAS storage (from name token).", "nas_truenas"},
	{"freenas", "family", "high", "Likely FreeNAS / TrueNAS legacy (from name token).", "nas_freenas"},
	{"asustor", "family", "high", "Likely ASUSTOR NAS (from name token).", "nas_asustor"},
	{"terramaster", "family", "medium", "Likely TerraMaster NAS (from name token).", "nas_terra"},
	{"wdmycloud", "family", "medium", "Likely Western Digital My Cloud (from name token).", "nas_wdmycloud"},
	{"mycloud", "family", "low", "Possibly Western Digital My Cloud (from name token).", "nas_mycloud"},
	{"readynas", "family", "medium", "Likely NETGEAR ReadyNAS (from name token).", "nas_readynas"},
	{"drobo", "family", "medium", "Likely Drobo storage (from name token).", "nas_drobo"},
	{"nas", "family", "low", "Possibly a NAS or file-server style hostname.", "nas_generic"},
	{"nextcloud", "family", "medium", "Likely Nextcloud server (from name token).", "nas_nextcloud"},

	// Single-board / lab
	{"raspberrypi", "family", "medium", "Likely Raspberry Pi (default hostname style).", "pi_raspberry"},
	{"raspberry", "family", "low", "Possibly Raspberry Pi (from name token).", "pi_raspberry_loose"},
	{"beaglebone", "family", "medium", "Likely BeagleBone embedded board (from name token).", "pi_beagle"},
	{"odroid", "family", "medium", "Likely ODROID SBC (from name token).", "pi_odroid"},
	{"rockpi", "family", "medium", "Likely ROCK Pi SBC (from name token).", "pi_rockpi"},
	{"jetson", "family", "medium", "Likely NVIDIA Jetson dev kit (from name token).", "pi_jetson"},

	// Home automation / hubs
	{"homeassistant", "family", "high", "Likely Home Assistant server (from name token).", "hub_ha"},
	{"home-assistant", "family", "high", "Likely Home Assistant (from name token).", "hub_ha_dash"},
	{"hassio", "family", "high", "Likely Home Assistant OS / add-on host (from name token).", "hub_hassio"},
	{"hass", "family", "low", "Possibly Home Assistant (short token; ambiguous).", "hub_hass_short"},
	{"smartthings", "family", "medium", "Likely Samsung SmartThings hub (from name token).", "hub_smartthings"},
	{"hubitat", "family", "high", "Likely Hubitat Elevation hub (from name token).", "hub_hubitat"},
	{"vera-", "family", "low", "Possibly Vera smart home controller (hostname prefix).", "hub_vera"},
	{"fibaro", "family", "medium", "Likely Fibaro home center (from name token).", "hub_fibaro"},
	{"zipato", "family", "medium", "Likely Zipato hub (from name token).", "hub_zipato"},
	{"homebridge", "family", "high", "Likely Homebridge (from name token).", "hap_homebridge"},
	{"hoobs", "family", "medium", "Likely HOOBS Homebridge distro (from name token).", "hap_hoobs"},
	{"openhab", "family", "medium", "Likely openHAB server (from name token).", "hub_openhab"},
	{"domoticz", "family", "medium", "Likely Domoticz server (from name token).", "hub_domoticz"},

	// HomeKit / mDNS ecosystem
	{"_hap._tcp", "family", "medium", "Likely HomeKit accessory (mDNS HAP service).", "hap_mdns_hap"},
	{"_homekit._tcp", "family", "medium", "Likely HomeKit bridge (mDNS).", "hap_mdns_homekit"},
	{"homekit", "family", "medium", "Likely Apple HomeKit accessory (from name token).", "hap_homekit"},

	// Lighting / plugs / HVAC
	{"hue", "family", "medium", "Likely Philips Hue bridge or accessory (from name token).", "hap_hue"},
	{"philips-hue", "family", "high", "Likely Philips Hue (from name token).", "hap_philips_hue"},
	{"nanoleaf", "family", "high", "Likely Nanoleaf panels (from name token).", "iot_nanoleaf"},
	{"lifx", "family", "high", "Likely LIFX smart bulb (from name token).", "iot_lifx"},
	{"govee", "family", "medium", "Likely Govee LED / IoT (from name token).", "iot_govee"},
	{"yeelight", "family", "medium", "Likely Yeelight bulb or strip (from name token).", "iot_yeelight"},
	{"meross", "family", "medium", "Likely Meross smart plug or switch (from name token).", "iot_meross"},
	{"kasa", "family", "medium", "Likely TP-Link Kasa smart device (from name token).", "iot_kasa"},
	{"tapo", "family", "medium", "Likely TP-Link Tapo camera or plug (from name token).", "iot_tapo"},
	{"gosund", "family", "medium", "Likely Gosund / Tuya-class plug (from name token).", "iot_gosund"},
	{"teckin", "family", "medium", "Likely Teckin smart plug (from name token).", "iot_teckin"},
	{"shelly", "family", "medium", "Likely Shelly Wi-Fi relay / sensor (from name token).", "iot_shelly"},
	{"tasmota", "family", "high", "Likely Tasmota firmware device (from name token).", "iot_tasmota"},
	{"esphome", "family", "high", "Likely ESPHome (from name token).", "iot_esphome"},
	{"esp_", "family", "low", "Possibly Espressif / ESPHome-class device (hostname pattern).", "iot_esp"},
	{"tuya", "family", "low", "Possibly Tuya-class smart device (from name token).", "iot_tuya"},
	{"wiz_", "family", "medium", "Likely WiZ connected light (from hostname prefix).", "iot_wiz"},
	{"lutron", "family", "medium", "Likely Lutron Caséta or RA2 (from name token).", "iot_lutron"},
	{"bond-", "family", "low", "Possibly Bond bridge for RF fans (hostname prefix).", "iot_bond"},
	{"switchbot", "family", "medium", "Likely SwitchBot bot / hub (from name token).", "iot_switchbot"},
	{"sensibo", "family", "medium", "Likely Sensibo AC controller (from name token).", "iot_sensibo"},
	{"tado", "family", "medium", "Likely tado° thermostat (from name token).", "iot_tado"},
	{"ecobee", "family", "medium", "Likely ecobee thermostat (from name token).", "iot_ecobee"},
	{"nest-", "family", "low", "Possibly Google Nest-class device (from name prefix).", "nest_prefix"},
	{"honeywell", "family", "low", "Possibly Honeywell thermostat or TCC bridge (from name token).", "iot_honeywell"},

	// Audio
	{"sonos", "family", "high", "Likely Sonos speaker (from name token).", "audio_sonos"},
	{"_sonos._tcp", "family", "high", "Likely Sonos (mDNS service type).", "audio_mdns_sonos"},
	{"bose", "family", "medium", "Likely Bose speaker or soundbar (from name token).", "audio_bose"},
	{"soundbar", "family", "low", "Possibly TV soundbar (generic hostname).", "audio_soundbar"},
	{"heos", "family", "medium", "Likely Denon HEOS speaker (from name token).", "audio_heos"},
	{"denon", "family", "medium", "Likely Denon AV receiver or HEOS (from name token).", "audio_denon"},
	{"yamaha", "family", "low", "Possibly Yamaha AV receiver (from name token).", "audio_yamaha"},
	{"onkyo", "family", "low", "Possibly Onkyo AV receiver (from name token).", "audio_onkyo"},
	{"sony-", "family", "low", "Possibly Sony TV or audio (hostname prefix).", "audio_sony_prefix"},
	{"volumio", "family", "high", "Likely Volumio music player (from name token).", "audio_volumio"},
	{"moode", "family", "medium", "Likely moOde audio player (from name token).", "audio_moode"},
	{"roon", "family", "medium", "Likely Roon audio core or bridge (from name token).", "audio_roon"},
	{"bluesound", "family", "medium", "Likely Bluesound speaker (from name token).", "audio_bluesound"},
	{"_spotify-connect._tcp", "family", "medium", "Likely Spotify Connect device (mDNS).", "media_spotify_connect"},

	// Cameras / NVR / doorbells
	{"wyze", "family", "medium", "Likely Wyze camera or plug (from name token).", "iot_wyze"},
	{"reolink", "family", "medium", "Likely Reolink camera or NVR (from name token).", "cam_reolink"},
	{"amcrest", "family", "medium", "Likely Amcrest camera or NVR (from name token).", "cam_amcrest"},
	{"hikvision", "family", "medium", "Likely Hikvision camera or NVR (from name token).", "cam_hikvision"},
	{"hik-", "family", "low", "Possibly Hikvision device (hostname prefix).", "cam_hik_prefix"},
	{"dahua", "family", "medium", "Likely Dahua camera or NVR (from name token).", "cam_dahua"},
	{"ubiquiti", "family", "low", "Possibly Ubiquiti Protect camera or console (from name token).", "cam_ubiquiti"},
	{"g4-", "family", "low", "Possibly UniFi Protect G4 camera (hostname token).", "cam_unifi_g4"},
	{"blink", "family", "medium", "Likely Blink camera (from name token).", "cam_blink"},
	{"arlo", "family", "medium", "Likely Arlo camera or hub (from name token).", "cam_arlo"},
	{"ring-", "family", "low", "Possibly Ring camera or doorbell (from name prefix).", "cam_ring"},
	{"eufy", "family", "medium", "Likely eufy Security camera or robovac (from name token).", "cam_eufy"},
	{"annke", "family", "medium", "Likely Annke DVR/NVR (from name token).", "cam_annke"},
	{"swann", "family", "medium", "Likely Swann DVR/NVR (from name token).", "cam_swann"},
	{"foscam", "family", "medium", "Likely Foscam IP camera (from name token).", "cam_foscam"},
	{"axis-", "family", "low", "Possibly Axis network camera (hostname prefix).", "cam_axis"},
	{"uniview", "family", "medium", "Likely Uniview IP camera (from name token).", "cam_uniview"},

	// Locks / garage
	{"august", "family", "medium", "Possibly August or Yale smart lock bridge (from name token).", "lock_august"},
	{"yale-", "family", "low", "Possibly Yale smart lock (hostname prefix).", "lock_yale"},
	{"schlage", "family", "medium", "Likely Schlage Encode / Wi-Fi lock bridge (from name token).", "lock_schlage"},
	{"myq", "family", "medium", "Likely Chamberlain myQ garage hub (from name token).", "garage_myq"},
	{"chamberlain", "family", "low", "Possibly Chamberlain / LiftMaster garage (from name token).", "garage_chamberlain"},
	{"tailscale", "family", "medium", "Likely Tailscale subnet router or exit node (from name token).", "vpn_tailscale"},
	{"wireguard", "family", "medium", "Likely WireGuard VPN endpoint (from name token).", "vpn_wireguard"},

	// Vacuum / floorcare
	{"roomba", "family", "high", "Likely iRobot Roomba (from name token).", "vac_roomba"},
	{"irobot", "family", "high", "Likely iRobot vacuum or mop (from name token).", "vac_irobot"},
	{"roborock", "family", "high", "Likely Roborock vacuum (from name token).", "vac_roborock"},
	{"dreame", "family", "medium", "Likely Dreame vacuum (from name token).", "vac_dreame"},
	{"ecovacs", "family", "medium", "Likely Ecovacs Deebot (from name token).", "vac_ecovacs"},
	{"neato", "family", "medium", "Likely Neato Botvac (from name token).", "vac_neato"},
	{"shark", "family", "low", "Possibly Shark IQ robot vacuum (from name token).", "vac_shark"},

	// Printers / scanners
	{"brw", "family", "low", "Possibly Brother network printer (common mDNS hostname prefix).", "printer_brother_brw"},
	{"brother", "family", "low", "Possibly Brother printer (from name token).", "printer_brother"},
	{"canon", "family", "low", "Possibly Canon printer or camera (from name token).", "printer_canon"},
	{"pixma", "family", "medium", "Likely Canon PIXMA printer (from name token).", "printer_pixma"},
	{"epson", "family", "low", "Possibly Epson printer (from name token).", "printer_epson"},
	{"deskjet", "family", "medium", "Likely HP DeskJet printer (from name token).", "printer_deskjet"},
	{"laserjet", "family", "medium", "Likely HP LaserJet printer (from name token).", "printer_laserjet"},
	{"officejet", "family", "medium", "Likely HP OfficeJet printer (from name token).", "printer_officejet"},
	{"hp-", "family", "low", "Possibly HP printer or PC (hostname prefix).", "printer_hp_prefix"},
	{"xerox", "family", "medium", "Likely Xerox printer or MFP (from name token).", "printer_xerox"},
	{"kyocera", "family", "medium", "Likely Kyocera printer (from name token).", "printer_kyocera"},
	{"ricoh", "family", "medium", "Likely Ricoh printer or MFP (from name token).", "printer_ricoh"},
	{"_ipp._tcp", "family", "medium", "Likely IPP network printer (mDNS service type).", "printer_mdns_ipp"},
	{"_printer._tcp", "family", "medium", "Likely network printer (mDNS service type).", "printer_mdns_printer"},
	{"_scanner._tcp", "family", "medium", "Likely network scanner (mDNS service type).", "printer_mdns_scanner"},

	// Media servers
	{"plex", "family", "medium", "Likely Plex media server (from name token).", "media_plex"},
	{"jellyfin", "family", "medium", "Likely Jellyfin server (from name token).", "media_jellyfin"},
	{"emby", "family", "medium", "Likely Emby server (from name token).", "media_emby"},
	{"kodi", "family", "medium", "Likely Kodi HTPC (from name token).", "media_kodi"},
	{"xbmc", "family", "medium", "Likely Kodi/XBMC (from name token).", "media_xbmc"},
	{"airplay", "family", "medium", "Likely AirPlay-capable device (from name or service hint).", "media_airplay"},

	// Energy / solar
	{"fronius", "family", "high", "Likely Fronius solar inverter or gateway (from name token).", "energy_fronius"},
	{"enphase", "family", "medium", "Likely Enphase Envoy / microinverter gateway (from name token).", "energy_enphase"},
	{"solaredge", "family", "medium", "Likely SolarEdge inverter gateway (from name token).", "energy_solaredge"},
	{"sma-", "family", "low", "Possibly SMA solar inverter (hostname prefix).", "energy_sma"},
	{"growatt", "family", "medium", "Likely Growatt inverter (from name token).", "energy_growatt"},
	{"tesla", "family", "low", "Possibly Tesla Powerwall gateway or vehicle hostname.", "energy_tesla"},

	// Wearables / health (rare on LAN)
	{"fitbit", "family", "low", "Possibly Fitbit sync dongle or scale (from name token).", "wear_fitbit"},
	{"garmin", "family", "low", "Possibly Garmin device sync (from name token).", "wear_garmin"},

	// Docker / dev / monitoring (homelab)
	{"docker", "family", "low", "Possibly Docker host or registry in hostname.", "dev_docker"},
	{"portainer", "family", "medium", "Likely Portainer UI (from name token).", "dev_portainer"},
	{"grafana", "family", "medium", "Likely Grafana server (from name token).", "dev_grafana"},
	{"prometheus", "family", "low", "Possibly Prometheus server (from name token).", "dev_prometheus"},
	{"proxmox", "family", "high", "Likely Proxmox VE host (from name token).", "dev_proxmox"},
	{"esxi", "family", "medium", "Likely VMware ESXi host (from name token).", "dev_esxi"},
}
